server {
    listen 80;
    server_name vault.brswindows.labl;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name vault.brswindows.lab;

    ssl_certificate /etc/nginx/ssl/vault.brswindows.lab.crt;
    ssl_certificate_key /etc/nginx/ssl/vault.brswindows.lab.key;

    client_max_body_size 128M;

    location / {
        proxy_pass http://vaultwarden:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
