[req]
default_bits = 4096
prompt = no
default_md = sha256
distinguished_name = dn
x509_extensions = v3_req

[dn]
C = ES
ST = MADRID
L = Local
O = notnull
OU = IT
CN = vault.brswindows.lab

[v3_req]
subjectAltName = @alt_names

[alt_names]
DNS.1 = vault.brswindows.lab
IP.1 = 10.0.2.30

#Ajustar el CN, DNS.1 y IP.1 al dominio que vamos usar para acceder al panel web del vaultwarden
